### ISSUE TITLE
DFL needs another bump due to complete breakage in new Steam Client

### ISSUE THREAD

**Issue by TiZ-HugLife** [safijari/Shotty#11]
[See this specific comment](https://github.com/SteamDeckHomebrew/decky-loader/issues/597#issuecomment-1987138946) of SteamDeckHomebrew/decky-loader#597. Thanks for your time.

**Comment by safijari** [comment]
There's a version in the testing store that should work correctly.

Please leave feedback here so that it can be moved to production

https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/561

**Comment by TiZ-HugLife** [comment]
Thanks very kindly.
