### ISSUE TITLE
Suggestion: Allow option to choose between copy and link

### ISSUE THREAD

**Issue by OpenBagTwo** [safijari/Shotty#3]
Given that I'd potentially want to use your plugin as a way of doing actual backups 

When I ask the plugin to aggregate my screenshots

Then I'd like for there to be able to specify in the UI whether I want the aggregated files to be hard links (your default, as I understand it), symlinks or straight-up independent copies

So that if I choose to modify a screenshot in am external photo editor or delete the screenshot from the Steam UI that it only affects the original / aggregated copy if I've so chosen.

---

As with my other suggestion, the python is simple, and I'd be happy to learn the Javascript if this is a contribution you're open to having.

**Comment by safijari** [comment]
You can double check this but I'm pretty sure hardlinks already achieve what you want. If you save over a hard link it'll start pointing towards a new inode. The old inode will still exist and will continue to do so until the original file (which mind you is also a hardlink, all files in Linux are) is pointing to it.

I'm not opposed to options but I don't think they're needed here.
