### ISSUE TITLE
Ability to disable 'screenshot symlinked' notifications

### ISSUE THREAD

**Issue by rasitayaz** [safijari/Shotty#5]
Great plugin, it would be nice to have the option to disable the notifications, two notifications per screenshot can become a bit annoying.

**Comment by Perdonium** [comment]
If you still need or for anyone in the future : this can be removed by modifying directly the index.js file.
```
cd homebrew/plugins/Shotty/dist
chmod +w index.js
nano index.js
```
Then find line 363
```
 await serverApi.toaster.toast({
                    title: "Shotty",
                    body: "Screenshot Symlinked",
                    duration: 1000,
                    critical: true
                });
```
and add comment markers /* */ around like this
```
/*
 await serverApi.toaster.toast({
                    title: "Shotty",
                    body: "Screenshot Symlinked",
                    duration: 1000,
                    critical: true
                });
*/
```

and voilà!

**Comment by safijari** [comment]
This is already fixed in the testing version of the plugin and now that a tester has left a comment it should be merged soon.
