### ISSUE TITLE
Get app name from steamclient api

### ISSUE THREAD

**Issue by codehz** [safijari/Shotty#7]
So we can get localized game name instead of hard coded at 'https://github.com/safijari/Shotty/blob/main/defaults/appidmap.json'

I found the api to get app info is `SteamClient.InstallFolder.GetInstallFolders`
Although the name does not imply that it can get the appname, the return value's `vecapps` field contains all installed game information (and the name is localized).

It is also works for non-steam apps

**Comment by safijari** [comment]
I'm reasonably sure I'm using the json file as a backup only. Are you getting wrong names?
