### ISSUE TITLE
symlink "most_recent" screenshot

### ISSUE THREAD

**Issue by NyaomiDEV** [safijari/Shotty#8]
My request is to symlink the most recent screenshot so that I can resolve the link to get a path like `/home/deck/Images/Screenshots/[Game]/[Screenshot].png`.

I intend this to help me code a Telegram bot that just shoots me the screenshot from the game, but it has access to the deck via SSH, so it can resolve symlinks but not go into the nitty gritty of whatever Steam is doing.

**Comment by safijari** [comment]
It's a hard link and you can find the other file using this method

https://unix.stackexchange.com/questions/201920/how-to-find-all-hard-links-to-a-given-file
